language: node_js
node_js:
  - "7"

services:
  - docker

before_install:
  - echo $DOCKER_PASSWORD | docker login -u=$DOCKER_USERNAME --password-stdin

script:
  - sed -i "s/application_url/$APPLICATION_URL/g" config.js
  - sed -i "s/gdrive_client_id/$GOOGLE_CLIENTID/" config.js
  - sed -i "s/gdrive_client_secret/$GOOGLE_CLIENTSECRET/" config.js
  - sed -i "s/dropbox_client_id/$DROPBOX_CLIENTID/" config.js
  - npm run image
  - npm run publish